version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: ${APP_CONTAINER_NAME}
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www/html
  postgres:
    build:
        context: .
        dockerfile: .docker/postgresql/Dockerfile
    ports: 
        - "${DB_PORT}:${DB_PORT}"
    image: ${DB_CONTAINER_NAME}
    container_name: ${DB_CONTAINER_NAME}
    environment:
        - PGDATA=${DB_DATA}
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
  redis:
    build:
        context: .
        dockerfile: .docker/redis/Dockerfile
    ports:
        - "${REDIS_PORT}:${REDIS_PORT}"
    image: ${REDIS_CONTAINER_NAME}
    container_name: ${REDIS_CONTAINER_NAME}
